FROM nginx:1.21.1-alpine
LABEL maintainer="Igor Nehoroshev <hi@neigor.me>"

RUN apk add --no-cache nginx-mod-mail && mkdir /etc/nginx/mail-enabled
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 465/tcp 993/tcp 995/tcp
