#!/bin/bash
set -e

rm -rf venv
python3.8 -m virtualenv venv

# Install all requirements
./venv/bin/pip install -r requirements.txt
./venv/bin/pip install -r .ci/auth-requirements.txt
./venv/bin/pip install -r .ci/style-requirements.txt
./venv/bin/pip install -r .ci/security-requirements.txt
./venv/bin/pip install -r docs-requirements.txt
# Install radon for `metrics` script
./venv/bin/pip install radon
# Install kolombo package
./venv/bin/pip install .
