#!/bin/bash
set -e

rm -rf venv
python3.9 -m virtualenv venv

# Install all requirements
./venv/bin/pip install --no-cache-dir -r requirements.txt
./venv/bin/pip install --no-cache-dir -r .ci/auth-requirements.txt
./venv/bin/pip install --no-cache-dir -r .ci/style-requirements.txt
./venv/bin/pip install --no-cache-dir -r .ci/security-requirements.txt
# Install radon for `metrics` script
./venv/bin/pip install --no-cache-dir radon
# Install kolombo package
./venv/bin/pip install --no-cache-dir .
