#!/bin/bash
set -e

# Go to repository root directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${DIR}/.."

find kolombo -type f -name "*.py[co]" -delete
find kolombo -type d -name __pycache__ -delete

rm -rf dist build kolombo.egg-info

python3.8 setup.py sdist
python3.8 setup.py bdist_wheel
python3.9 setup.py bdist_wheel
twine upload dist/*

rm -rf dist build kolombo.egg-info
